name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.**
    paths-ignore:
      - "docs/**"
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    strategy:
      matrix:
        project:
          - name: go
            dir: goast
            prefix: libgoast

          - name: rust
            dir: rustast
            prefix: libcpgrust

        target:
          - arch: amd64
            os: linux
            runs-on: ubuntu-latest
            ext: so

          - arch: arm64
            os: linux
            runs-on: [self-hosted, Linux, ARM64]
            ext: so

          - arch: arm64
            os: macos
            runs-on: macos-latest
            ext: dylib

          - arch: amd64
            os: macos
            runs-on: macos-latest
            ext: dylib

          - arch: amd64
            os: windows
            runs-on: windows-latest
            ext: dll
    runs-on: ${{ matrix.target.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        if: matrix.project.name == 'go'
        uses: actions/setup-go@v5
        with:
          go-version-file: ./goast/go.mod
          cache-dependency-path: ./goast/go.sum

      - name: Setup Rust
        if: matrix.project.name == 'rust'
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        shell: bash
        working-directory: ${{ matrix.project.dir }}
        run: |
          ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project.prefix }}-${{ matrix.target.arch }}.${{ matrix.target.ext }}
          path: ${{ matrix.project.dir }}/${{ matrix.project.prefix }}-${{ matrix.target.arch }}.${{ matrix.target.ext }}

  publish:
    runs-on: ubuntu-latest

    needs:
      - build

    if: startsWith(github.ref, 'refs/tags/v') &&
        !contains(github.ref, 'beta') &&
        !contains(github.ref, 'alpha')

    steps:
      - name: Determine Version
        run: |
          # determine version from tag
          export VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          if [[ $VERSION != v* ]]
          then
            export VERSION=""
            echo "Building version-less (main or feature branch)"
          else
            # make version more Java-friendly by dropping the 'v'
            export VERSION=${VERSION:1:${#VERSION}}
            echo "Building as ${VERSION}"
          fi
          # store version in GitHub environment file
          echo "version=$VERSION" >> $GITHUB_ENV

      #
      # Go artifacts
      #

      - uses: actions/download-artifact@v4
        with:
          name: libgoast-arm64.dylib
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: libgoast-amd64.dylib
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: libgoast-amd64.so
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: libgoast-arm64.so
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: libgoast-amd64.dll
          path: .

      #
      # Rust artifacts
      #

      - uses: actions/download-artifact@v4
        with:
          name: libcpgrust-arm64.dylib
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: libcpgrust-amd64.dylib
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: libcpgrust-arm64.so
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: libcpgrust-amd64.so
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: libcpgrust-amd64.dll
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.version }}
          draft: false
          prerelease: false
          files: |
            libgoast-arm64.dylib
            libgoast-amd64.dylib
            libgoast-amd64.so
            libgoast-arm64.so
            libgoast-amd64.dll
            libcpgrust-arm64.dylib
            libcpgrust-amd64.dylib
            libcpgrust-arm64.so
            libcpgrust-amd64.so
            libcpgrust-amd64.dll
